/**
 * Error codes used throughout DisherIO application.
 * These codes are shared between backend and frontend to ensure consistency.
 * 
 * Usage in backend:
 *   throw new Error(ErrorCode.ITEM_NOT_FOUND);
 * 
 * Usage in frontend:
 *   if (error.errorCode === ErrorCode.ITEM_NOT_FOUND) { ... }
 */

export enum ErrorCode {
  // Authentication & Authorization
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_PIN = 'INVALID_PIN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  FORBIDDEN = 'FORBIDDEN',
  REQUIRES_POS_AUTHORIZATION = 'REQUIRES_POS_AUTHORIZATION',
  REQUIRES_AUTHORIZATION = 'REQUIRES_AUTHORIZATION',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  SERVER_CONFIGURATION_ERROR = 'SERVER_CONFIGURATION_ERROR',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  AUTH_RATE_LIMIT_EXCEEDED = 'AUTH_RATE_LIMIT_EXCEEDED',
  QR_RATE_LIMIT_EXCEEDED = 'QR_RATE_LIMIT_EXCEEDED',
  QR_BRUTE_FORCE_DETECTED = 'QR_BRUTE_FORCE_DETECTED',

  // Resource Not Found
  NOT_FOUND = 'NOT_FOUND',
  DISH_NOT_FOUND = 'DISH_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  TOTEM_NOT_FOUND = 'TOTEM_NOT_FOUND',
  RESTAURANT_NOT_FOUND = 'RESTAURANT_NOT_FOUND',
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  TABLE_NOT_FOUND = 'TABLE_NOT_FOUND',

  // Business Logic Errors
  DISH_NOT_AVAILABLE = 'DISH_NOT_AVAILABLE',
  SESSION_NOT_ACTIVE = 'SESSION_NOT_ACTIVE',
  SESSION_EXPIRED_STATE = 'SESSION_EXPIRED_STATE',
  ORDER_ALREADY_PAID = 'ORDER_ALREADY_PAID',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  NO_ITEMS_TO_PAY = 'NO_ITEMS_TO_PAY',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  TOTEM_NOT_ACTIVE = 'TOTEM_NOT_ACTIVE',
  TOTEM_QR_INVALID = 'TOTEM_QR_INVALID',
  RESTAURANT_NOT_ACTIVE = 'RESTAURANT_NOT_ACTIVE',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  CANNOT_DELETE_ITEM_NOT_ORDERED = 'CANNOT_DELETE_ITEM_NOT_ORDERED',
  ITEM_NOT_FOUND_OR_ALREADY_PROCESSED = 'ITEM_NOT_FOUND_OR_ALREADY_PROCESSED',
  UPDATE_FAILED = 'UPDATE_FAILED',
  CATEGORY_HAS_DISHES = 'CATEGORY_HAS_DISHES',

  // Validation Errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_PRICE = 'INVALID_PRICE',
  INVALID_ID_FORMAT = 'INVALID_ID_FORMAT',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // Data Conflicts
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',

  // Server Errors
  SERVER_ERROR = 'SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  DASHBOARD_ERROR = 'DASHBOARD_ERROR',
  LOGS_ERROR = 'LOGS_ERROR',
  LOGS_USERS_ERROR = 'LOGS_USERS_ERROR',
}

/**
 * HTTP status codes mapped to error codes for backend use
 */
export const ERROR_HTTP_STATUS_MAP: Record<ErrorCode, number> = {
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.INVALID_PIN]: 401,
  [ErrorCode.INVALID_TOKEN]: 401,
  [ErrorCode.SESSION_EXPIRED]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.REQUIRES_POS_AUTHORIZATION]: 403,
  [ErrorCode.REQUIRES_AUTHORIZATION]: 403,
  [ErrorCode.AUTHENTICATION_REQUIRED]: 401,
  [ErrorCode.SERVER_CONFIGURATION_ERROR]: 500,

  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.AUTH_RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.QR_RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.QR_BRUTE_FORCE_DETECTED]: 429,

  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.DISH_NOT_FOUND]: 404,
  [ErrorCode.CATEGORY_NOT_FOUND]: 404,
  [ErrorCode.SESSION_NOT_FOUND]: 404,
  [ErrorCode.ORDER_NOT_FOUND]: 404,
  [ErrorCode.ITEM_NOT_FOUND]: 404,
  [ErrorCode.PAYMENT_NOT_FOUND]: 404,
  [ErrorCode.TICKET_NOT_FOUND]: 404,
  [ErrorCode.TOTEM_NOT_FOUND]: 404,
  [ErrorCode.RESTAURANT_NOT_FOUND]: 404,
  [ErrorCode.STAFF_NOT_FOUND]: 404,
  [ErrorCode.ROLE_NOT_FOUND]: 404,
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.CUSTOMER_NOT_FOUND]: 404,
  [ErrorCode.TABLE_NOT_FOUND]: 404,

  [ErrorCode.DISH_NOT_AVAILABLE]: 400,
  [ErrorCode.SESSION_NOT_ACTIVE]: 400,
  [ErrorCode.SESSION_EXPIRED_STATE]: 401,
  [ErrorCode.ORDER_ALREADY_PAID]: 400,
  [ErrorCode.ORDER_CANCELLED]: 400,
  [ErrorCode.NO_ITEMS_TO_PAY]: 400,
  [ErrorCode.PAYMENT_FAILED]: 400,
  [ErrorCode.TOTEM_NOT_ACTIVE]: 400,
  [ErrorCode.TOTEM_QR_INVALID]: 400,
  [ErrorCode.RESTAURANT_NOT_ACTIVE]: 400,
  [ErrorCode.INVALID_STATE_TRANSITION]: 400,
  [ErrorCode.CANNOT_DELETE_ITEM_NOT_ORDERED]: 400,
  [ErrorCode.ITEM_NOT_FOUND_OR_ALREADY_PROCESSED]: 400,
  [ErrorCode.UPDATE_FAILED]: 500,
  [ErrorCode.CATEGORY_HAS_DISHES]: 409,

  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.INVALID_PRICE]: 400,
  [ErrorCode.INVALID_ID_FORMAT]: 400,
  [ErrorCode.INVALID_FILE_TYPE]: 400,
  [ErrorCode.FILE_TOO_LARGE]: 400,

  [ErrorCode.USER_ALREADY_EXISTS]: 409,
  [ErrorCode.DUPLICATE_RESOURCE]: 409,

  [ErrorCode.SERVER_ERROR]: 500,
  [ErrorCode.DATABASE_ERROR]: 500,
  [ErrorCode.UPLOAD_FAILED]: 400,
  [ErrorCode.DASHBOARD_ERROR]: 500,
  [ErrorCode.LOGS_ERROR]: 500,
  [ErrorCode.LOGS_USERS_ERROR]: 500,
};

/**
 * Type guard to check if a string is a valid ErrorCode
 */
export function isErrorCode(code: string): code is ErrorCode {
  return Object.values(ErrorCode).includes(code as ErrorCode);
}
