/**
 * Error codes used throughout DisherIO application.
 * These codes are shared between backend and frontend to ensure consistency.
 *
 * Usage in backend:
 *   throw new Error(ErrorCode.ITEM_NOT_FOUND);
 *
 * Usage in frontend:
 *   if (error.errorCode === ErrorCode.ITEM_NOT_FOUND) { ... }
 */

export enum ErrorCode {
  // Authentication & Authorization
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  FORBIDDEN = 'FORBIDDEN',
  REQUIRES_POS_AUTHORIZATION = 'REQUIRES_POS_AUTHORIZATION',
  REQUIRES_AUTHORIZATION = 'REQUIRES_AUTHORIZATION',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  SERVER_CONFIGURATION_ERROR = 'SERVER_CONFIGURATION_ERROR',
  AMBIGUOUS_USERNAME = 'AMBIGUOUS_USERNAME',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  AUTH_RATE_LIMIT_EXCEEDED = 'AUTH_RATE_LIMIT_EXCEEDED',
  API_RATE_LIMIT_EXCEEDED = 'API_RATE_LIMIT_EXCEEDED',
  STRICT_RATE_LIMIT_EXCEEDED = 'STRICT_RATE_LIMIT_EXCEEDED',
  UPLOAD_RATE_LIMIT_EXCEEDED = 'UPLOAD_RATE_LIMIT_EXCEEDED',
  QR_RATE_LIMIT_EXCEEDED = 'QR_RATE_LIMIT_EXCEEDED',
  QR_BRUTE_FORCE_DETECTED = 'QR_BRUTE_FORCE_DETECTED',

  // Resource Not Found
  NOT_FOUND = 'NOT_FOUND',
  DISH_NOT_FOUND = 'DISH_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  TOTEM_NOT_FOUND = 'TOTEM_NOT_FOUND',
  RESTAURANT_NOT_FOUND = 'RESTAURANT_NOT_FOUND',
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',

  // Business Logic Errors
  DISH_NOT_AVAILABLE = 'DISH_NOT_AVAILABLE',
  SESSION_NOT_ACTIVE = 'SESSION_NOT_ACTIVE',
  ACTIVE_SESSION_EXISTS = 'ACTIVE_SESSION_EXISTS',
  ORDER_LIMIT_REACHED = 'ORDER_LIMIT_REACHED',
  ORDER_INTERVAL_ACTIVE = 'ORDER_INTERVAL_ACTIVE',
  ORDER_ALREADY_PAID = 'ORDER_ALREADY_PAID',
  SESSION_ALREADY_PAID = 'SESSION_ALREADY_PAID',
  NO_ITEMS_TO_PAY = 'NO_ITEMS_TO_PAY',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  CANNOT_DELETE_ITEM_NOT_ORDERED = 'CANNOT_DELETE_ITEM_NOT_ORDERED',
  ITEM_NOT_FOUND_OR_ALREADY_PROCESSED = 'ITEM_NOT_FOUND_OR_ALREADY_PROCESSED',
  UPDATE_FAILED = 'UPDATE_FAILED',
  CATEGORY_HAS_DISHES = 'CATEGORY_HAS_DISHES',
  SESSION_HAS_ITEMS = 'SESSION_HAS_ITEMS',
  LAST_ADMIN = 'LAST_ADMIN',

  // Validation Errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_PRICE = 'INVALID_PRICE',
  INVALID_ID_FORMAT = 'INVALID_ID_FORMAT',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  NO_FILE_UPLOADED = 'NO_FILE_UPLOADED',
  INVALID_FILE = 'INVALID_FILE',
  INVALID_IMAGE_DIMENSIONS = 'INVALID_IMAGE_DIMENSIONS',
  UNEXPECTED_FIELD = 'UNEXPECTED_FIELD',
  TOO_MANY_FILES = 'TOO_MANY_FILES',
  UPLOAD_ERROR = 'UPLOAD_ERROR',
  CUSTOMER_NAME_REQUIRED = 'CUSTOMER_NAME_REQUIRED',

  // Data Conflicts
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  CUSTOMER_NAME_TAKEN = 'CUSTOMER_NAME_TAKEN',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  OPERATION_IN_PROGRESS = 'OPERATION_IN_PROGRESS',

  // Server Errors
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  SERVER_ERROR = 'SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
}

/**
 * HTTP status codes mapped to error codes for backend use
 */
export const ERROR_HTTP_STATUS_MAP: Record<ErrorCode, number> = {
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.INVALID_TOKEN]: 401,
  [ErrorCode.SESSION_EXPIRED]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.REQUIRES_POS_AUTHORIZATION]: 403,
  [ErrorCode.REQUIRES_AUTHORIZATION]: 403,
  [ErrorCode.AUTHENTICATION_REQUIRED]: 401,
  [ErrorCode.SERVER_CONFIGURATION_ERROR]: 500,
  [ErrorCode.AMBIGUOUS_USERNAME]: 400,

  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.AUTH_RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.API_RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.STRICT_RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.UPLOAD_RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.QR_RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.QR_BRUTE_FORCE_DETECTED]: 429,

  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.DISH_NOT_FOUND]: 404,
  [ErrorCode.CATEGORY_NOT_FOUND]: 404,
  [ErrorCode.SESSION_NOT_FOUND]: 404,
  [ErrorCode.ORDER_NOT_FOUND]: 404,
  [ErrorCode.ITEM_NOT_FOUND]: 404,
  [ErrorCode.PAYMENT_NOT_FOUND]: 404,
  [ErrorCode.TICKET_NOT_FOUND]: 404,
  [ErrorCode.TOTEM_NOT_FOUND]: 404,
  [ErrorCode.RESTAURANT_NOT_FOUND]: 404,
  [ErrorCode.STAFF_NOT_FOUND]: 404,
  [ErrorCode.ROLE_NOT_FOUND]: 404,
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.CUSTOMER_NOT_FOUND]: 404,

  [ErrorCode.DISH_NOT_AVAILABLE]: 400,
  [ErrorCode.SESSION_NOT_ACTIVE]: 400,
  [ErrorCode.ACTIVE_SESSION_EXISTS]: 409,
  [ErrorCode.ORDER_LIMIT_REACHED]: 409,
  [ErrorCode.ORDER_INTERVAL_ACTIVE]: 409,
  [ErrorCode.ORDER_ALREADY_PAID]: 400,
  [ErrorCode.SESSION_ALREADY_PAID]: 409,
  [ErrorCode.NO_ITEMS_TO_PAY]: 400,
  [ErrorCode.INVALID_STATE_TRANSITION]: 400,
  [ErrorCode.CANNOT_DELETE_ITEM_NOT_ORDERED]: 400,
  [ErrorCode.ITEM_NOT_FOUND_OR_ALREADY_PROCESSED]: 400,
  [ErrorCode.UPDATE_FAILED]: 500,
  [ErrorCode.CATEGORY_HAS_DISHES]: 409,
  [ErrorCode.SESSION_HAS_ITEMS]: 409,
  [ErrorCode.LAST_ADMIN]: 409,

  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.INVALID_PRICE]: 400,
  [ErrorCode.INVALID_ID_FORMAT]: 400,
  [ErrorCode.INVALID_FILE_TYPE]: 400,
  [ErrorCode.FILE_TOO_LARGE]: 400,
  [ErrorCode.NO_FILE_UPLOADED]: 400,
  [ErrorCode.INVALID_FILE]: 400,
  [ErrorCode.INVALID_IMAGE_DIMENSIONS]: 400,
  [ErrorCode.UNEXPECTED_FIELD]: 400,
  [ErrorCode.TOO_MANY_FILES]: 400,
  [ErrorCode.UPLOAD_ERROR]: 400,
  [ErrorCode.CUSTOMER_NAME_REQUIRED]: 400,

  [ErrorCode.USER_ALREADY_EXISTS]: 409,
  [ErrorCode.CUSTOMER_NAME_TAKEN]: 409,
  [ErrorCode.DUPLICATE_RESOURCE]: 409,
  [ErrorCode.IDEMPOTENCY_CONFLICT]: 409,
  [ErrorCode.OPERATION_IN_PROGRESS]: 409,

  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.SERVER_ERROR]: 500,
  [ErrorCode.DATABASE_ERROR]: 500,
};

/**
 * Type guard to check if a string is a valid ErrorCode
 */
export function isErrorCode(code: string): code is ErrorCode {
  return Object.values(ErrorCode).includes(code as ErrorCode);
}
