/** @type {import('tailwindcss').Config} */
const m3Color = (name) => ({ opacityValue }) => {
  const color = `var(--mat-sys-${name})`;
  if (opacityValue === undefined) {
    return color;
  }

  return `color-mix(in srgb, ${color} calc(${opacityValue} * 100%), transparent)`;
};

const disherColor = (name) => ({ opacityValue }) => {
  const color = `var(--disher-${name})`;
  if (opacityValue === undefined) {
    return color;
  }

  return `color-mix(in srgb, ${color} calc(${opacityValue} * 100%), transparent)`;
};

module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{html,ts,scss}',
  ],
  theme: {
    extend: {
      colors: {
        // M3 semantic colors mapped to full CSS color custom properties
        // generated by Angular Material's mat.theme().
        // Usage: bg-primary, text-on-surface, border-outline, etc.
        primary: {
          DEFAULT: m3Color('primary'),
          container: m3Color('primary-container'),
          // Legacy tonal aliases for backward compat during migration (Phases 2-4)
          50: m3Color('primary-container'),
          100: m3Color('primary-container'),
          600: m3Color('primary'),
          700: m3Color('primary'),
          dark: m3Color('primary'),
        },
        'on-primary': {
          DEFAULT: m3Color('on-primary'),
          container: m3Color('on-primary-container'),
        },
        secondary: {
          DEFAULT: m3Color('secondary'),
          container: m3Color('secondary-container'),
        },
        'on-secondary': {
          DEFAULT: m3Color('on-secondary'),
          container: m3Color('on-secondary-container'),
        },
        tertiary: {
          DEFAULT: m3Color('tertiary'),
          container: m3Color('tertiary-container'),
        },
        'on-tertiary': {
          DEFAULT: m3Color('on-tertiary'),
          container: m3Color('on-tertiary-container'),
        },
        error: {
          DEFAULT: m3Color('error'),
          container: m3Color('error-container'),
        },
        'on-error': {
          DEFAULT: m3Color('on-error'),
          container: m3Color('on-error-container'),
        },
        // Surface hierarchy (M3 has 5 container levels)
        surface: {
          DEFAULT: m3Color('surface'),
          dim: m3Color('surface-dim'),
          bright: m3Color('surface-bright'),
          'container-lowest': m3Color('surface-container-lowest'),
          'container-low': m3Color('surface-container-low'),
          container: m3Color('surface-container'),
          'container-high': m3Color('surface-container-high'),
          'container-highest': m3Color('surface-container-highest'),
          // Legacy aliases for backward compat during migration (Phases 2-4)
          muted: m3Color('surface-container-low'),
          line: m3Color('outline-variant'),
          dark: m3Color('surface-container'),
          'dark-muted': m3Color('surface-container-low'),
          'dark-line': m3Color('outline-variant'),
        },
        'on-surface': {
          DEFAULT: m3Color('on-surface'),
          variant: m3Color('on-surface-variant'),
        },
        outline: {
          DEFAULT: m3Color('outline'),
          variant: m3Color('outline-variant'),
        },
        'inverse-surface': m3Color('inverse-surface'),
        'inverse-on-surface': m3Color('inverse-on-surface'),
        'inverse-primary': m3Color('inverse-primary'),
        scrim: m3Color('scrim'),
        // Custom status: success (not in M3 default)
        success: {
          DEFAULT: disherColor('success'),
          container: disherColor('success-container'),
        },
        'on-success': {
          DEFAULT: disherColor('on-success'),
          container: disherColor('on-success-container'),
        },
      },
      boxShadow: {
        // M3 elevation levels
        'disher-0': 'var(--disher-elevation-0)',
        'disher-1': 'var(--disher-elevation-1)',
        'disher-2': 'var(--disher-elevation-2)',
        'disher-3': 'var(--disher-elevation-3)',
        'disher-4': 'var(--disher-elevation-4)',
        'disher-5': 'var(--disher-elevation-5)',
        // Legacy aliases for backward compat
        'material-sm': 'var(--disher-elevation-1)',
        'material-md': 'var(--disher-elevation-2)',
      },
      borderRadius: {
        'disher-xs': 'var(--disher-shape-xs)',
        'disher-sm': 'var(--disher-shape-sm)',
        'disher-md': 'var(--disher-shape-md)',
        'disher-lg': 'var(--disher-shape-lg)',
        'disher-xl': 'var(--disher-shape-xl)',
        'disher-full': 'var(--disher-shape-full)',
      },
      transitionTimingFunction: {
        'disher-standard': 'var(--disher-easing-standard)',
        'disher-emphasized': 'var(--disher-easing-emphasized)',
        'disher-decel': 'var(--disher-easing-emphasized-decelerate)',
        'disher-accel': 'var(--disher-easing-emphasized-accelerate)',
      },
      transitionDuration: {
        'disher-short-1': 'var(--disher-duration-short-1)',
        'disher-short-2': 'var(--disher-duration-short-2)',
        'disher-short-3': 'var(--disher-duration-short-3)',
        'disher-short-4': 'var(--disher-duration-short-4)',
        'disher-medium-1': 'var(--disher-duration-medium-1)',
        'disher-medium-2': 'var(--disher-duration-medium-2)',
        'disher-medium-3': 'var(--disher-duration-medium-3)',
        'disher-medium-4': 'var(--disher-duration-medium-4)',
        'disher-long-1': 'var(--disher-duration-long-1)',
        'disher-long-2': 'var(--disher-duration-long-2)',
        'disher-long-3': 'var(--disher-duration-long-3)',
        'disher-long-4': 'var(--disher-duration-long-4)',
      },
      fontFamily: {
        sans: ['Roboto', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
