#!/bin/bash

# Disher.io - Full Installer v2.7.0

# Styles
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Initial checks
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Por favor, ejecuta el script como root (sudo ./install.sh)${NC}"
  echo -e "${RED}Please run as root (sudo ./install.sh)${NC}"
  exit 1
fi

echo -e "${CYAN}============================================${NC}"
echo -e "${CYAN}         DISHER.IO - INSTALLER              ${NC}"
echo -e "${CYAN}============================================${NC}"

# 1. Language Selection
echo -e "\nSelecciona el idioma / Select language:"
echo -e "1) Español"
echo -e "2) English"
read -p "Opcion [1-2] (default: 1): " LANG_OPT

if [ "$LANG_OPT" = "2" ]; then
    MSG_DOM="[1/6] Domain Configuration"
    MSG_DOM_PROMPT="Enter your domain (e.g. app.disher.io): "
    MSG_SEC="[2/6] Configuring Security..."
    MSG_ENV="[3/6] Saving Configuration..."
    MSG_DOCKER="[4/6] Checking Docker..."
    MSG_SRV="[5/6] Starting Services..."
    MSG_INIT="[6/6] Configuring Initial Store..."
    MSG_UPD="DISHER.IO UPDATED SUCCESSFULLY"
    MSG_INST="DISHER.IO INSTALLED SUCCESSFULLY"
    MSG_CRED="--- Initial Credentials (save in a secure place) ---"
    MSG_USRADM="Admin User: "
    MSG_PWDADM="Admin Password: "
    MSG_USRWT="Waiter User: "
    MSG_PWDWT="Waiter Password: "
    MSG_ACCESS="Access: "
    MSG_ERR_DOCK="Docker Compose is required but not installed. Please install it first."
else
    MSG_DOM="[1/6] Configuración de Dominio"
    MSG_DOM_PROMPT="Introduce tu dominio (ej: app.disher.io): "
    MSG_SEC="[2/6] Configurando Seguridad..."
    MSG_ENV="[3/6] Guardando Configuración..."
    MSG_DOCKER="[4/6] Comprobando Docker..."
    MSG_SRV="[5/6] Levantando Servicios..."
    MSG_INIT="[6/6] Configurando Tienda Inicial..."
    MSG_UPD="DISHER.IO ACTUALIZADO CORRECTAMENTE"
    MSG_INST="DISHER.IO INSTALADO CORRECTAMENTE"
    MSG_CRED="--- Credenciales Iniciales (guardar en lugar seguro) ---"
    MSG_USRADM="Usuario Admin: "
    MSG_PWDADM="Contraseña Admin: "
    MSG_USRWT="Usuario Camarero: "
    MSG_PWDWT="Contraseña Camarero: "
    MSG_ACCESS="Acceso: "
    MSG_ERR_DOCK="Se requiere Docker Compose. Por favor, instálalo primero."
fi

# 2. Domain
echo -e "\n${CYAN}${MSG_DOM}${NC}"
read -p "${MSG_DOM_PROMPT}" CADDY_DOMAIN
if [ -z "$CADDY_DOMAIN" ]; then
    CADDY_DOMAIN="localhost"
fi

# 3. Security
echo -e "\n${CYAN}${MSG_SEC}${NC}"
JWT_SECRET=$(openssl rand -base64 32)
MONGO_PASS=$(openssl rand -base64 16)
MONGODB_URI="mongodb://admin:${MONGO_PASS}@database:27017/disher?authSource=admin"

ADMIN_PASS=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 12)
WAITER_PASS=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | head -c 8)

# 4. Environment
echo -e "\n${CYAN}${MSG_ENV}${NC}"
cat > .env <<EOF
# Auto-generated by Disher Installer
NODE_ENV=production
PORT=3000

# Security
JWT_SECRET=${JWT_SECRET}

# Database
MONGODB_URI=${MONGODB_URI}
MONGO_INITDB_ROOT_USERNAME=admin
MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}

# Domain
CADDY_DOMAIN=${CADDY_DOMAIN}
EOF

# 5. Docker Detection
echo -e "\n${CYAN}${MSG_DOCKER}${NC}"
if command -v docker-compose &> /dev/null; then
    DOCKER_CMD="docker-compose"
elif docker compose version &> /dev/null; then
    DOCKER_CMD="docker compose"
else
    echo -e "${RED}${MSG_ERR_DOCK}${NC}"
    exit 1
fi
echo -e "${GREEN}Using: ${DOCKER_CMD}${NC}"

# 6. Infrastructure
echo -e "\n${CYAN}${MSG_SRV}${NC}"
$DOCKER_CMD down --remove-orphans || true
$DOCKER_CMD up -d --build

# 7. Initial Store Setup
echo -e "\n${CYAN}${MSG_INIT}${NC}"
# Wait for backend and database to be ready
sleep 15
$DOCKER_CMD exec -e MONGO_URI="$MONGODB_URI" \
               -e INIT_ADMIN_PASS="$ADMIN_PASS" \
               -e INIT_WAITER_PASS="$WAITER_PASS" \
               backend sh -c "node init-store.js"

# 8. Summary
echo -e "\n${GREEN}============================================${NC}"
echo -e "${GREEN}   ${MSG_INST}${NC}"
echo -e "${GREEN}============================================${NC}"
echo -e "  ${MSG_ACCESS}https://${CADDY_DOMAIN}"

echo -e "\n${YELLOW}${MSG_CRED}${NC}"
echo -e "  ${MSG_USRADM}${CYAN}admin${NC}"
echo -e "  ${MSG_PWDADM}${CYAN}$ADMIN_PASS${NC}"
echo -e "\n  ${MSG_USRWT}${CYAN}waiter${NC}"
echo -e "  ${MSG_PWDWT}${CYAN}$WAITER_PASS${NC}"

echo -e "\n${GREEN}Listo! / Done!${NC}\n"
